//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ../Grammar/Bos.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="BosParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IBosListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.startRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStartRule([NotNull] BosParser.StartRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.startRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStartRule([NotNull] BosParser.StartRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModule([NotNull] BosParser.ModuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModule([NotNull] BosParser.ModuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.moduleReferences"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleReferences([NotNull] BosParser.ModuleReferencesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.moduleReferences"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleReferences([NotNull] BosParser.ModuleReferencesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.moduleImports"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleImports([NotNull] BosParser.ModuleImportsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.moduleImports"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleImports([NotNull] BosParser.ModuleImportsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.moduleReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleReference([NotNull] BosParser.ModuleReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.moduleReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleReference([NotNull] BosParser.ModuleReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.moduleReferenceValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleReferenceValue([NotNull] BosParser.ModuleReferenceValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.moduleReferenceValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleReferenceValue([NotNull] BosParser.ModuleReferenceValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.moduleReferenceComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleReferenceComponent([NotNull] BosParser.ModuleReferenceComponentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.moduleReferenceComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleReferenceComponent([NotNull] BosParser.ModuleReferenceComponentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.moduleHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleHeader([NotNull] BosParser.ModuleHeaderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.moduleHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleHeader([NotNull] BosParser.ModuleHeaderContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.moduleConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleConfig([NotNull] BosParser.ModuleConfigContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.moduleConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleConfig([NotNull] BosParser.ModuleConfigContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.moduleConfigElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleConfigElement([NotNull] BosParser.ModuleConfigElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.moduleConfigElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleConfigElement([NotNull] BosParser.ModuleConfigElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.moduleAttributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleAttributes([NotNull] BosParser.ModuleAttributesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.moduleAttributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleAttributes([NotNull] BosParser.ModuleAttributesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.moduleOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleOptions([NotNull] BosParser.ModuleOptionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.moduleOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleOptions([NotNull] BosParser.ModuleOptionsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>optionBaseStmt</c>
	/// labeled alternative in <see cref="BosParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionBaseStmt([NotNull] BosParser.OptionBaseStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>optionBaseStmt</c>
	/// labeled alternative in <see cref="BosParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionBaseStmt([NotNull] BosParser.OptionBaseStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>optionCompareStmt</c>
	/// labeled alternative in <see cref="BosParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionCompareStmt([NotNull] BosParser.OptionCompareStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>optionCompareStmt</c>
	/// labeled alternative in <see cref="BosParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionCompareStmt([NotNull] BosParser.OptionCompareStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>optionExplicitStmt</c>
	/// labeled alternative in <see cref="BosParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionExplicitStmt([NotNull] BosParser.OptionExplicitStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>optionExplicitStmt</c>
	/// labeled alternative in <see cref="BosParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionExplicitStmt([NotNull] BosParser.OptionExplicitStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>optionPrivateModuleStmt</c>
	/// labeled alternative in <see cref="BosParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionPrivateModuleStmt([NotNull] BosParser.OptionPrivateModuleStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>optionPrivateModuleStmt</c>
	/// labeled alternative in <see cref="BosParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionPrivateModuleStmt([NotNull] BosParser.OptionPrivateModuleStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.moduleBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleBody([NotNull] BosParser.ModuleBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.moduleBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleBody([NotNull] BosParser.ModuleBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.moduleBodyElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleBodyElement([NotNull] BosParser.ModuleBodyElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.moduleBodyElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleBodyElement([NotNull] BosParser.ModuleBodyElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassBody([NotNull] BosParser.ClassBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassBody([NotNull] BosParser.ClassBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.classBodyElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassBodyElement([NotNull] BosParser.ClassBodyElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.classBodyElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassBodyElement([NotNull] BosParser.ClassBodyElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.controlProperties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlProperties([NotNull] BosParser.ControlPropertiesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.controlProperties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlProperties([NotNull] BosParser.ControlPropertiesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.cp_Properties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCp_Properties([NotNull] BosParser.Cp_PropertiesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.cp_Properties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCp_Properties([NotNull] BosParser.Cp_PropertiesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.cp_SingleProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCp_SingleProperty([NotNull] BosParser.Cp_SinglePropertyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.cp_SingleProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCp_SingleProperty([NotNull] BosParser.Cp_SinglePropertyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.cp_PropertyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCp_PropertyName([NotNull] BosParser.Cp_PropertyNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.cp_PropertyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCp_PropertyName([NotNull] BosParser.Cp_PropertyNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.cp_PropertyValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCp_PropertyValue([NotNull] BosParser.Cp_PropertyValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.cp_PropertyValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCp_PropertyValue([NotNull] BosParser.Cp_PropertyValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.cp_NestedProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCp_NestedProperty([NotNull] BosParser.Cp_NestedPropertyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.cp_NestedProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCp_NestedProperty([NotNull] BosParser.Cp_NestedPropertyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.cp_ControlType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCp_ControlType([NotNull] BosParser.Cp_ControlTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.cp_ControlType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCp_ControlType([NotNull] BosParser.Cp_ControlTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.cp_ControlIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCp_ControlIdentifier([NotNull] BosParser.Cp_ControlIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.cp_ControlIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCp_ControlIdentifier([NotNull] BosParser.Cp_ControlIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.moduleBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleBlock([NotNull] BosParser.ModuleBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.moduleBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleBlock([NotNull] BosParser.ModuleBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.importStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportStmt([NotNull] BosParser.ImportStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.importStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportStmt([NotNull] BosParser.ImportStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.attributeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeStmt([NotNull] BosParser.AttributeStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.attributeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeStmt([NotNull] BosParser.AttributeStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] BosParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] BosParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.blockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockStmt([NotNull] BosParser.BlockStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.blockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockStmt([NotNull] BosParser.BlockStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.appActivateStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAppActivateStmt([NotNull] BosParser.AppActivateStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.appActivateStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAppActivateStmt([NotNull] BosParser.AppActivateStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.beepStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBeepStmt([NotNull] BosParser.BeepStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.beepStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBeepStmt([NotNull] BosParser.BeepStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.chDirStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChDirStmt([NotNull] BosParser.ChDirStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.chDirStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChDirStmt([NotNull] BosParser.ChDirStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.chDriveStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChDriveStmt([NotNull] BosParser.ChDriveStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.chDriveStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChDriveStmt([NotNull] BosParser.ChDriveStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.classStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassStmt([NotNull] BosParser.ClassStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.classStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassStmt([NotNull] BosParser.ClassStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.closeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCloseStmt([NotNull] BosParser.CloseStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.closeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCloseStmt([NotNull] BosParser.CloseStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.constStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstStmt([NotNull] BosParser.ConstStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.constStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstStmt([NotNull] BosParser.ConstStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.constSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstSubStmt([NotNull] BosParser.ConstSubStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.constSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstSubStmt([NotNull] BosParser.ConstSubStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.dateStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDateStmt([NotNull] BosParser.DateStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.dateStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDateStmt([NotNull] BosParser.DateStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.declareStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclareStmt([NotNull] BosParser.DeclareStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.declareStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclareStmt([NotNull] BosParser.DeclareStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.deftypeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeftypeStmt([NotNull] BosParser.DeftypeStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.deftypeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeftypeStmt([NotNull] BosParser.DeftypeStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.deleteSettingStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeleteSettingStmt([NotNull] BosParser.DeleteSettingStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.deleteSettingStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeleteSettingStmt([NotNull] BosParser.DeleteSettingStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.doLoopStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoLoopStmt([NotNull] BosParser.DoLoopStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.doLoopStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoLoopStmt([NotNull] BosParser.DoLoopStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.endStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEndStmt([NotNull] BosParser.EndStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.endStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEndStmt([NotNull] BosParser.EndStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.enumerationStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumerationStmt([NotNull] BosParser.EnumerationStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.enumerationStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumerationStmt([NotNull] BosParser.EnumerationStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.enumerationStmt_Constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumerationStmt_Constant([NotNull] BosParser.EnumerationStmt_ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.enumerationStmt_Constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumerationStmt_Constant([NotNull] BosParser.EnumerationStmt_ConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.eraseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEraseStmt([NotNull] BosParser.EraseStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.eraseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEraseStmt([NotNull] BosParser.EraseStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.errorStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterErrorStmt([NotNull] BosParser.ErrorStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.errorStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitErrorStmt([NotNull] BosParser.ErrorStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.eventStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventStmt([NotNull] BosParser.EventStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.eventStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventStmt([NotNull] BosParser.EventStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.exitStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExitStmt([NotNull] BosParser.ExitStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.exitStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExitStmt([NotNull] BosParser.ExitStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.filecopyStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFilecopyStmt([NotNull] BosParser.FilecopyStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.filecopyStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFilecopyStmt([NotNull] BosParser.FilecopyStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.forEachStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForEachStmt([NotNull] BosParser.ForEachStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.forEachStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForEachStmt([NotNull] BosParser.ForEachStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.forNextStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForNextStmt([NotNull] BosParser.ForNextStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.forNextStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForNextStmt([NotNull] BosParser.ForNextStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.functionStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionStmt([NotNull] BosParser.FunctionStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.functionStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionStmt([NotNull] BosParser.FunctionStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.getStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGetStmt([NotNull] BosParser.GetStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.getStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGetStmt([NotNull] BosParser.GetStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.goSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGoSubStmt([NotNull] BosParser.GoSubStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.goSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGoSubStmt([NotNull] BosParser.GoSubStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.goToStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGoToStmt([NotNull] BosParser.GoToStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.goToStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGoToStmt([NotNull] BosParser.GoToStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>inlineIfThenElse</c>
	/// labeled alternative in <see cref="BosParser.ifThenElseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInlineIfThenElse([NotNull] BosParser.InlineIfThenElseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>inlineIfThenElse</c>
	/// labeled alternative in <see cref="BosParser.ifThenElseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInlineIfThenElse([NotNull] BosParser.InlineIfThenElseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>blockIfThenElse</c>
	/// labeled alternative in <see cref="BosParser.ifThenElseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockIfThenElse([NotNull] BosParser.BlockIfThenElseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>blockIfThenElse</c>
	/// labeled alternative in <see cref="BosParser.ifThenElseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockIfThenElse([NotNull] BosParser.BlockIfThenElseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.ifBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfBlockStmt([NotNull] BosParser.IfBlockStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.ifBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfBlockStmt([NotNull] BosParser.IfBlockStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.ifConditionStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfConditionStmt([NotNull] BosParser.IfConditionStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.ifConditionStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfConditionStmt([NotNull] BosParser.IfConditionStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.ifElseIfBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfElseIfBlockStmt([NotNull] BosParser.IfElseIfBlockStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.ifElseIfBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfElseIfBlockStmt([NotNull] BosParser.IfElseIfBlockStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.ifElseBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfElseBlockStmt([NotNull] BosParser.IfElseBlockStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.ifElseBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfElseBlockStmt([NotNull] BosParser.IfElseBlockStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.implementsStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplementsStmt([NotNull] BosParser.ImplementsStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.implementsStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplementsStmt([NotNull] BosParser.ImplementsStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.inputStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInputStmt([NotNull] BosParser.InputStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.inputStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInputStmt([NotNull] BosParser.InputStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.killStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKillStmt([NotNull] BosParser.KillStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.killStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKillStmt([NotNull] BosParser.KillStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.letStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLetStmt([NotNull] BosParser.LetStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.letStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLetStmt([NotNull] BosParser.LetStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.lineInputStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLineInputStmt([NotNull] BosParser.LineInputStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.lineInputStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLineInputStmt([NotNull] BosParser.LineInputStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.loadStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoadStmt([NotNull] BosParser.LoadStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.loadStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoadStmt([NotNull] BosParser.LoadStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.lockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLockStmt([NotNull] BosParser.LockStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.lockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLockStmt([NotNull] BosParser.LockStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.lsetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLsetStmt([NotNull] BosParser.LsetStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.lsetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLsetStmt([NotNull] BosParser.LsetStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.macroIfThenElseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMacroIfThenElseStmt([NotNull] BosParser.MacroIfThenElseStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.macroIfThenElseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMacroIfThenElseStmt([NotNull] BosParser.MacroIfThenElseStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.macroIfBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMacroIfBlockStmt([NotNull] BosParser.MacroIfBlockStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.macroIfBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMacroIfBlockStmt([NotNull] BosParser.MacroIfBlockStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.macroElseIfBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMacroElseIfBlockStmt([NotNull] BosParser.MacroElseIfBlockStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.macroElseIfBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMacroElseIfBlockStmt([NotNull] BosParser.MacroElseIfBlockStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.macroElseBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMacroElseBlockStmt([NotNull] BosParser.MacroElseBlockStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.macroElseBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMacroElseBlockStmt([NotNull] BosParser.MacroElseBlockStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.midStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMidStmt([NotNull] BosParser.MidStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.midStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMidStmt([NotNull] BosParser.MidStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.mkdirStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMkdirStmt([NotNull] BosParser.MkdirStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.mkdirStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMkdirStmt([NotNull] BosParser.MkdirStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.nameStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameStmt([NotNull] BosParser.NameStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.nameStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameStmt([NotNull] BosParser.NameStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.onErrorStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOnErrorStmt([NotNull] BosParser.OnErrorStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.onErrorStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOnErrorStmt([NotNull] BosParser.OnErrorStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.onGoToStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOnGoToStmt([NotNull] BosParser.OnGoToStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.onGoToStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOnGoToStmt([NotNull] BosParser.OnGoToStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.onGoSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOnGoSubStmt([NotNull] BosParser.OnGoSubStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.onGoSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOnGoSubStmt([NotNull] BosParser.OnGoSubStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.openStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpenStmt([NotNull] BosParser.OpenStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.openStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpenStmt([NotNull] BosParser.OpenStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.outputList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutputList([NotNull] BosParser.OutputListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.outputList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutputList([NotNull] BosParser.OutputListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.outputList_Expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutputList_Expression([NotNull] BosParser.OutputList_ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.outputList_Expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutputList_Expression([NotNull] BosParser.OutputList_ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.printStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrintStmt([NotNull] BosParser.PrintStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.printStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrintStmt([NotNull] BosParser.PrintStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.propertyGetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyGetStmt([NotNull] BosParser.PropertyGetStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.propertyGetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyGetStmt([NotNull] BosParser.PropertyGetStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.propertySetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertySetStmt([NotNull] BosParser.PropertySetStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.propertySetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertySetStmt([NotNull] BosParser.PropertySetStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.propertyLetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyLetStmt([NotNull] BosParser.PropertyLetStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.propertyLetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyLetStmt([NotNull] BosParser.PropertyLetStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.putStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPutStmt([NotNull] BosParser.PutStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.putStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPutStmt([NotNull] BosParser.PutStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.raiseEventStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRaiseEventStmt([NotNull] BosParser.RaiseEventStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.raiseEventStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRaiseEventStmt([NotNull] BosParser.RaiseEventStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.randomizeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRandomizeStmt([NotNull] BosParser.RandomizeStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.randomizeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRandomizeStmt([NotNull] BosParser.RandomizeStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.redimStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRedimStmt([NotNull] BosParser.RedimStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.redimStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRedimStmt([NotNull] BosParser.RedimStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.redimSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRedimSubStmt([NotNull] BosParser.RedimSubStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.redimSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRedimSubStmt([NotNull] BosParser.RedimSubStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.resetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResetStmt([NotNull] BosParser.ResetStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.resetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResetStmt([NotNull] BosParser.ResetStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.resumeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResumeStmt([NotNull] BosParser.ResumeStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.resumeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResumeStmt([NotNull] BosParser.ResumeStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStmt([NotNull] BosParser.ReturnStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStmt([NotNull] BosParser.ReturnStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.rmdirStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRmdirStmt([NotNull] BosParser.RmdirStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.rmdirStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRmdirStmt([NotNull] BosParser.RmdirStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.rsetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRsetStmt([NotNull] BosParser.RsetStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.rsetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRsetStmt([NotNull] BosParser.RsetStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.savepictureStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSavepictureStmt([NotNull] BosParser.SavepictureStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.savepictureStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSavepictureStmt([NotNull] BosParser.SavepictureStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.saveSettingStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSaveSettingStmt([NotNull] BosParser.SaveSettingStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.saveSettingStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSaveSettingStmt([NotNull] BosParser.SaveSettingStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.seekStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSeekStmt([NotNull] BosParser.SeekStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.seekStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSeekStmt([NotNull] BosParser.SeekStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.selectCaseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectCaseStmt([NotNull] BosParser.SelectCaseStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.selectCaseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectCaseStmt([NotNull] BosParser.SelectCaseStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.sC_Case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSC_Case([NotNull] BosParser.SC_CaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.sC_Case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSC_Case([NotNull] BosParser.SC_CaseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>caseCondElse</c>
	/// labeled alternative in <see cref="BosParser.sC_Cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseCondElse([NotNull] BosParser.CaseCondElseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>caseCondElse</c>
	/// labeled alternative in <see cref="BosParser.sC_Cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseCondElse([NotNull] BosParser.CaseCondElseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>caseCondExpr</c>
	/// labeled alternative in <see cref="BosParser.sC_Cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseCondExpr([NotNull] BosParser.CaseCondExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>caseCondExpr</c>
	/// labeled alternative in <see cref="BosParser.sC_Cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseCondExpr([NotNull] BosParser.CaseCondExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>caseCondExprIs</c>
	/// labeled alternative in <see cref="BosParser.sC_CondExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseCondExprIs([NotNull] BosParser.CaseCondExprIsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>caseCondExprIs</c>
	/// labeled alternative in <see cref="BosParser.sC_CondExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseCondExprIs([NotNull] BosParser.CaseCondExprIsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>caseCondExprValue</c>
	/// labeled alternative in <see cref="BosParser.sC_CondExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseCondExprValue([NotNull] BosParser.CaseCondExprValueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>caseCondExprValue</c>
	/// labeled alternative in <see cref="BosParser.sC_CondExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseCondExprValue([NotNull] BosParser.CaseCondExprValueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>caseCondExprTo</c>
	/// labeled alternative in <see cref="BosParser.sC_CondExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseCondExprTo([NotNull] BosParser.CaseCondExprToContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>caseCondExprTo</c>
	/// labeled alternative in <see cref="BosParser.sC_CondExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseCondExprTo([NotNull] BosParser.CaseCondExprToContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.sendkeysStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSendkeysStmt([NotNull] BosParser.SendkeysStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.sendkeysStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSendkeysStmt([NotNull] BosParser.SendkeysStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.setattrStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetattrStmt([NotNull] BosParser.SetattrStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.setattrStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetattrStmt([NotNull] BosParser.SetattrStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.setStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetStmt([NotNull] BosParser.SetStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.setStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetStmt([NotNull] BosParser.SetStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.stopStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStopStmt([NotNull] BosParser.StopStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.stopStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStopStmt([NotNull] BosParser.StopStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.subStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubStmt([NotNull] BosParser.SubStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.subStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubStmt([NotNull] BosParser.SubStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.timeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTimeStmt([NotNull] BosParser.TimeStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.timeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTimeStmt([NotNull] BosParser.TimeStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.typeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeStmt([NotNull] BosParser.TypeStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.typeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeStmt([NotNull] BosParser.TypeStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.typeStmt_Element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeStmt_Element([NotNull] BosParser.TypeStmt_ElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.typeStmt_Element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeStmt_Element([NotNull] BosParser.TypeStmt_ElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.typeOfStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeOfStmt([NotNull] BosParser.TypeOfStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.typeOfStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeOfStmt([NotNull] BosParser.TypeOfStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.unloadStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnloadStmt([NotNull] BosParser.UnloadStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.unloadStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnloadStmt([NotNull] BosParser.UnloadStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.unlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnlockStmt([NotNull] BosParser.UnlockStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.unlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnlockStmt([NotNull] BosParser.UnlockStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsStruct</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsStruct([NotNull] BosParser.VsStructContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsStruct</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsStruct([NotNull] BosParser.VsStructContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsAdd</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsAdd([NotNull] BosParser.VsAddContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsAdd</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsAdd([NotNull] BosParser.VsAddContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsLt</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsLt([NotNull] BosParser.VsLtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsLt</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsLt([NotNull] BosParser.VsLtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsAddressOf</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsAddressOf([NotNull] BosParser.VsAddressOfContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsAddressOf</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsAddressOf([NotNull] BosParser.VsAddressOfContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsNew</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsNew([NotNull] BosParser.VsNewContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsNew</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsNew([NotNull] BosParser.VsNewContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsMult</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsMult([NotNull] BosParser.VsMultContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsMult</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsMult([NotNull] BosParser.VsMultContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsNegation</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsNegation([NotNull] BosParser.VsNegationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsNegation</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsNegation([NotNull] BosParser.VsNegationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsAssign</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsAssign([NotNull] BosParser.VsAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsAssign</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsAssign([NotNull] BosParser.VsAssignContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsDiv</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsDiv([NotNull] BosParser.VsDivContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsDiv</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsDiv([NotNull] BosParser.VsDivContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsLike</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsLike([NotNull] BosParser.VsLikeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsLike</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsLike([NotNull] BosParser.VsLikeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsPlus</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsPlus([NotNull] BosParser.VsPlusContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsPlus</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsPlus([NotNull] BosParser.VsPlusContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsNot</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsNot([NotNull] BosParser.VsNotContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsNot</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsNot([NotNull] BosParser.VsNotContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsGeq</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsGeq([NotNull] BosParser.VsGeqContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsGeq</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsGeq([NotNull] BosParser.VsGeqContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsTypeOf</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsTypeOf([NotNull] BosParser.VsTypeOfContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsTypeOf</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsTypeOf([NotNull] BosParser.VsTypeOfContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsICS</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsICS([NotNull] BosParser.VsICSContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsICS</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsICS([NotNull] BosParser.VsICSContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsNeq</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsNeq([NotNull] BosParser.VsNeqContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsNeq</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsNeq([NotNull] BosParser.VsNeqContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsXor</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsXor([NotNull] BosParser.VsXorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsXor</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsXor([NotNull] BosParser.VsXorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsAnd</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsAnd([NotNull] BosParser.VsAndContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsAnd</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsAnd([NotNull] BosParser.VsAndContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsPow</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsPow([NotNull] BosParser.VsPowContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsPow</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsPow([NotNull] BosParser.VsPowContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsLeq</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsLeq([NotNull] BosParser.VsLeqContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsLeq</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsLeq([NotNull] BosParser.VsLeqContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsIs</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsIs([NotNull] BosParser.VsIsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsIs</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsIs([NotNull] BosParser.VsIsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsMod</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsMod([NotNull] BosParser.VsModContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsMod</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsMod([NotNull] BosParser.VsModContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsAmp</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsAmp([NotNull] BosParser.VsAmpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsAmp</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsAmp([NotNull] BosParser.VsAmpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsOr</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsOr([NotNull] BosParser.VsOrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsOr</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsOr([NotNull] BosParser.VsOrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsMinus</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsMinus([NotNull] BosParser.VsMinusContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsMinus</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsMinus([NotNull] BosParser.VsMinusContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsLiteral</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsLiteral([NotNull] BosParser.VsLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsLiteral</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsLiteral([NotNull] BosParser.VsLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsEqv</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsEqv([NotNull] BosParser.VsEqvContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsEqv</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsEqv([NotNull] BosParser.VsEqvContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsImp</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsImp([NotNull] BosParser.VsImpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsImp</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsImp([NotNull] BosParser.VsImpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsGt</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsGt([NotNull] BosParser.VsGtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsGt</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsGt([NotNull] BosParser.VsGtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsEq</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsEq([NotNull] BosParser.VsEqContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsEq</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsEq([NotNull] BosParser.VsEqContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsMid</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsMid([NotNull] BosParser.VsMidContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsMid</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsMid([NotNull] BosParser.VsMidContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.variableStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableStmt([NotNull] BosParser.VariableStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.variableStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableStmt([NotNull] BosParser.VariableStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.variableListStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableListStmt([NotNull] BosParser.VariableListStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.variableListStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableListStmt([NotNull] BosParser.VariableListStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.variableSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableSubStmt([NotNull] BosParser.VariableSubStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.variableSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableSubStmt([NotNull] BosParser.VariableSubStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.whileWendStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileWendStmt([NotNull] BosParser.WhileWendStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.whileWendStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileWendStmt([NotNull] BosParser.WhileWendStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.widthStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWidthStmt([NotNull] BosParser.WidthStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.widthStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWidthStmt([NotNull] BosParser.WidthStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.withStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWithStmt([NotNull] BosParser.WithStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.withStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWithStmt([NotNull] BosParser.WithStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.writeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWriteStmt([NotNull] BosParser.WriteStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.writeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWriteStmt([NotNull] BosParser.WriteStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.explicitCallStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplicitCallStmt([NotNull] BosParser.ExplicitCallStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.explicitCallStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplicitCallStmt([NotNull] BosParser.ExplicitCallStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.eCS_ProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterECS_ProcedureCall([NotNull] BosParser.ECS_ProcedureCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.eCS_ProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitECS_ProcedureCall([NotNull] BosParser.ECS_ProcedureCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.eCS_MemberProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterECS_MemberProcedureCall([NotNull] BosParser.ECS_MemberProcedureCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.eCS_MemberProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitECS_MemberProcedureCall([NotNull] BosParser.ECS_MemberProcedureCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.implicitCallStmt_InBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplicitCallStmt_InBlock([NotNull] BosParser.ImplicitCallStmt_InBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.implicitCallStmt_InBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplicitCallStmt_InBlock([NotNull] BosParser.ImplicitCallStmt_InBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.iCS_B_ProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterICS_B_ProcedureCall([NotNull] BosParser.ICS_B_ProcedureCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.iCS_B_ProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitICS_B_ProcedureCall([NotNull] BosParser.ICS_B_ProcedureCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.iCS_B_MemberProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterICS_B_MemberProcedureCall([NotNull] BosParser.ICS_B_MemberProcedureCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.iCS_B_MemberProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitICS_B_MemberProcedureCall([NotNull] BosParser.ICS_B_MemberProcedureCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.implicitCallStmt_InStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplicitCallStmt_InStmt([NotNull] BosParser.ImplicitCallStmt_InStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.implicitCallStmt_InStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplicitCallStmt_InStmt([NotNull] BosParser.ImplicitCallStmt_InStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.iCS_S_VariableOrProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterICS_S_VariableOrProcedureCall([NotNull] BosParser.ICS_S_VariableOrProcedureCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.iCS_S_VariableOrProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitICS_S_VariableOrProcedureCall([NotNull] BosParser.ICS_S_VariableOrProcedureCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.iCS_S_ProcedureOrArrayCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterICS_S_ProcedureOrArrayCall([NotNull] BosParser.ICS_S_ProcedureOrArrayCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.iCS_S_ProcedureOrArrayCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitICS_S_ProcedureOrArrayCall([NotNull] BosParser.ICS_S_ProcedureOrArrayCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.iCS_S_NestedProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterICS_S_NestedProcedureCall([NotNull] BosParser.ICS_S_NestedProcedureCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.iCS_S_NestedProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitICS_S_NestedProcedureCall([NotNull] BosParser.ICS_S_NestedProcedureCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.iCS_S_MembersCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterICS_S_MembersCall([NotNull] BosParser.ICS_S_MembersCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.iCS_S_MembersCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitICS_S_MembersCall([NotNull] BosParser.ICS_S_MembersCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.iCS_S_MemberCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterICS_S_MemberCall([NotNull] BosParser.ICS_S_MemberCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.iCS_S_MemberCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitICS_S_MemberCall([NotNull] BosParser.ICS_S_MemberCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.iCS_S_DictionaryCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterICS_S_DictionaryCall([NotNull] BosParser.ICS_S_DictionaryCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.iCS_S_DictionaryCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitICS_S_DictionaryCall([NotNull] BosParser.ICS_S_DictionaryCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.argsCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgsCall([NotNull] BosParser.ArgsCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.argsCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgsCall([NotNull] BosParser.ArgsCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.argCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgCall([NotNull] BosParser.ArgCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.argCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgCall([NotNull] BosParser.ArgCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.dictionaryCallStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDictionaryCallStmt([NotNull] BosParser.DictionaryCallStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.dictionaryCallStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDictionaryCallStmt([NotNull] BosParser.DictionaryCallStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgList([NotNull] BosParser.ArgListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgList([NotNull] BosParser.ArgListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArg([NotNull] BosParser.ArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArg([NotNull] BosParser.ArgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.argDefaultValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgDefaultValue([NotNull] BosParser.ArgDefaultValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.argDefaultValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgDefaultValue([NotNull] BosParser.ArgDefaultValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.subscripts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubscripts([NotNull] BosParser.SubscriptsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.subscripts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubscripts([NotNull] BosParser.SubscriptsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.subscript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubscript([NotNull] BosParser.SubscriptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.subscript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubscript([NotNull] BosParser.SubscriptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.ambiguousIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAmbiguousIdentifier([NotNull] BosParser.AmbiguousIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.ambiguousIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAmbiguousIdentifier([NotNull] BosParser.AmbiguousIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.asTypeClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsTypeClause([NotNull] BosParser.AsTypeClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.asTypeClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsTypeClause([NotNull] BosParser.AsTypeClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.baseType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaseType([NotNull] BosParser.BaseTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.baseType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaseType([NotNull] BosParser.BaseTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.certainIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCertainIdentifier([NotNull] BosParser.CertainIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.certainIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCertainIdentifier([NotNull] BosParser.CertainIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.comparisonOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparisonOperator([NotNull] BosParser.ComparisonOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.comparisonOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparisonOperator([NotNull] BosParser.ComparisonOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.complexType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComplexType([NotNull] BosParser.ComplexTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.complexType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComplexType([NotNull] BosParser.ComplexTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.fieldLength"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldLength([NotNull] BosParser.FieldLengthContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.fieldLength"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldLength([NotNull] BosParser.FieldLengthContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.letterrange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLetterrange([NotNull] BosParser.LetterrangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.letterrange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLetterrange([NotNull] BosParser.LetterrangeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.lineLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLineLabel([NotNull] BosParser.LineLabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.lineLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLineLabel([NotNull] BosParser.LineLabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] BosParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] BosParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.publicPrivateVisibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPublicPrivateVisibility([NotNull] BosParser.PublicPrivateVisibilityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.publicPrivateVisibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPublicPrivateVisibility([NotNull] BosParser.PublicPrivateVisibilityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.publicPrivateGlobalVisibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPublicPrivateGlobalVisibility([NotNull] BosParser.PublicPrivateGlobalVisibilityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.publicPrivateGlobalVisibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPublicPrivateGlobalVisibility([NotNull] BosParser.PublicPrivateGlobalVisibilityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] BosParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] BosParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.typeHint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeHint([NotNull] BosParser.TypeHintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.typeHint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeHint([NotNull] BosParser.TypeHintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVisibility([NotNull] BosParser.VisibilityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVisibility([NotNull] BosParser.VisibilityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BosParser.ambiguousKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAmbiguousKeyword([NotNull] BosParser.AmbiguousKeywordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BosParser.ambiguousKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAmbiguousKeyword([NotNull] BosParser.AmbiguousKeywordContext context);
}
