//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ../Grammar/BOS.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="BOSParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IBOSListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.startRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStartRule([NotNull] BOSParser.StartRuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.startRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStartRule([NotNull] BOSParser.StartRuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModule([NotNull] BOSParser.ModuleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModule([NotNull] BOSParser.ModuleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.moduleReferences"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleReferences([NotNull] BOSParser.ModuleReferencesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.moduleReferences"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleReferences([NotNull] BOSParser.ModuleReferencesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.moduleReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleReference([NotNull] BOSParser.ModuleReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.moduleReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleReference([NotNull] BOSParser.ModuleReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.moduleReferenceValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleReferenceValue([NotNull] BOSParser.ModuleReferenceValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.moduleReferenceValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleReferenceValue([NotNull] BOSParser.ModuleReferenceValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.moduleReferenceComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleReferenceComponent([NotNull] BOSParser.ModuleReferenceComponentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.moduleReferenceComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleReferenceComponent([NotNull] BOSParser.ModuleReferenceComponentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.moduleHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleHeader([NotNull] BOSParser.ModuleHeaderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.moduleHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleHeader([NotNull] BOSParser.ModuleHeaderContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.moduleConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleConfig([NotNull] BOSParser.ModuleConfigContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.moduleConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleConfig([NotNull] BOSParser.ModuleConfigContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.moduleConfigElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleConfigElement([NotNull] BOSParser.ModuleConfigElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.moduleConfigElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleConfigElement([NotNull] BOSParser.ModuleConfigElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.moduleAttributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleAttributes([NotNull] BOSParser.ModuleAttributesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.moduleAttributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleAttributes([NotNull] BOSParser.ModuleAttributesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.moduleOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleOptions([NotNull] BOSParser.ModuleOptionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.moduleOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleOptions([NotNull] BOSParser.ModuleOptionsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>optionBaseStmt</c>
	/// labeled alternative in <see cref="BOSParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionBaseStmt([NotNull] BOSParser.OptionBaseStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>optionBaseStmt</c>
	/// labeled alternative in <see cref="BOSParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionBaseStmt([NotNull] BOSParser.OptionBaseStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>optionCompareStmt</c>
	/// labeled alternative in <see cref="BOSParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionCompareStmt([NotNull] BOSParser.OptionCompareStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>optionCompareStmt</c>
	/// labeled alternative in <see cref="BOSParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionCompareStmt([NotNull] BOSParser.OptionCompareStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>optionExplicitStmt</c>
	/// labeled alternative in <see cref="BOSParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionExplicitStmt([NotNull] BOSParser.OptionExplicitStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>optionExplicitStmt</c>
	/// labeled alternative in <see cref="BOSParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionExplicitStmt([NotNull] BOSParser.OptionExplicitStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>optionPrivateModuleStmt</c>
	/// labeled alternative in <see cref="BOSParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOptionPrivateModuleStmt([NotNull] BOSParser.OptionPrivateModuleStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>optionPrivateModuleStmt</c>
	/// labeled alternative in <see cref="BOSParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOptionPrivateModuleStmt([NotNull] BOSParser.OptionPrivateModuleStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.moduleBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleBody([NotNull] BOSParser.ModuleBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.moduleBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleBody([NotNull] BOSParser.ModuleBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.moduleBodyElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleBodyElement([NotNull] BOSParser.ModuleBodyElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.moduleBodyElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleBodyElement([NotNull] BOSParser.ModuleBodyElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.controlProperties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlProperties([NotNull] BOSParser.ControlPropertiesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.controlProperties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlProperties([NotNull] BOSParser.ControlPropertiesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.cp_Properties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCp_Properties([NotNull] BOSParser.Cp_PropertiesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.cp_Properties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCp_Properties([NotNull] BOSParser.Cp_PropertiesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.cp_SingleProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCp_SingleProperty([NotNull] BOSParser.Cp_SinglePropertyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.cp_SingleProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCp_SingleProperty([NotNull] BOSParser.Cp_SinglePropertyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.cp_PropertyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCp_PropertyName([NotNull] BOSParser.Cp_PropertyNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.cp_PropertyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCp_PropertyName([NotNull] BOSParser.Cp_PropertyNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.cp_PropertyValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCp_PropertyValue([NotNull] BOSParser.Cp_PropertyValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.cp_PropertyValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCp_PropertyValue([NotNull] BOSParser.Cp_PropertyValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.cp_NestedProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCp_NestedProperty([NotNull] BOSParser.Cp_NestedPropertyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.cp_NestedProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCp_NestedProperty([NotNull] BOSParser.Cp_NestedPropertyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.cp_ControlType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCp_ControlType([NotNull] BOSParser.Cp_ControlTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.cp_ControlType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCp_ControlType([NotNull] BOSParser.Cp_ControlTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.cp_ControlIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCp_ControlIdentifier([NotNull] BOSParser.Cp_ControlIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.cp_ControlIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCp_ControlIdentifier([NotNull] BOSParser.Cp_ControlIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.moduleBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterModuleBlock([NotNull] BOSParser.ModuleBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.moduleBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitModuleBlock([NotNull] BOSParser.ModuleBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.attributeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeStmt([NotNull] BOSParser.AttributeStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.attributeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeStmt([NotNull] BOSParser.AttributeStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] BOSParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] BOSParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.blockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockStmt([NotNull] BOSParser.BlockStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.blockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockStmt([NotNull] BOSParser.BlockStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.appActivateStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAppActivateStmt([NotNull] BOSParser.AppActivateStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.appActivateStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAppActivateStmt([NotNull] BOSParser.AppActivateStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.beepStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBeepStmt([NotNull] BOSParser.BeepStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.beepStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBeepStmt([NotNull] BOSParser.BeepStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.chDirStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChDirStmt([NotNull] BOSParser.ChDirStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.chDirStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChDirStmt([NotNull] BOSParser.ChDirStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.chDriveStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChDriveStmt([NotNull] BOSParser.ChDriveStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.chDriveStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChDriveStmt([NotNull] BOSParser.ChDriveStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.closeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCloseStmt([NotNull] BOSParser.CloseStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.closeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCloseStmt([NotNull] BOSParser.CloseStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.constStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstStmt([NotNull] BOSParser.ConstStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.constStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstStmt([NotNull] BOSParser.ConstStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.constSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstSubStmt([NotNull] BOSParser.ConstSubStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.constSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstSubStmt([NotNull] BOSParser.ConstSubStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.dateStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDateStmt([NotNull] BOSParser.DateStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.dateStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDateStmt([NotNull] BOSParser.DateStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.declareStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclareStmt([NotNull] BOSParser.DeclareStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.declareStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclareStmt([NotNull] BOSParser.DeclareStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.deftypeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeftypeStmt([NotNull] BOSParser.DeftypeStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.deftypeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeftypeStmt([NotNull] BOSParser.DeftypeStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.deleteSettingStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeleteSettingStmt([NotNull] BOSParser.DeleteSettingStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.deleteSettingStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeleteSettingStmt([NotNull] BOSParser.DeleteSettingStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.doLoopStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoLoopStmt([NotNull] BOSParser.DoLoopStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.doLoopStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoLoopStmt([NotNull] BOSParser.DoLoopStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.endStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEndStmt([NotNull] BOSParser.EndStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.endStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEndStmt([NotNull] BOSParser.EndStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.enumerationStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumerationStmt([NotNull] BOSParser.EnumerationStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.enumerationStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumerationStmt([NotNull] BOSParser.EnumerationStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.enumerationStmt_Constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumerationStmt_Constant([NotNull] BOSParser.EnumerationStmt_ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.enumerationStmt_Constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumerationStmt_Constant([NotNull] BOSParser.EnumerationStmt_ConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.eraseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEraseStmt([NotNull] BOSParser.EraseStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.eraseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEraseStmt([NotNull] BOSParser.EraseStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.errorStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterErrorStmt([NotNull] BOSParser.ErrorStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.errorStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitErrorStmt([NotNull] BOSParser.ErrorStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.eventStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventStmt([NotNull] BOSParser.EventStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.eventStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventStmt([NotNull] BOSParser.EventStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.exitStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExitStmt([NotNull] BOSParser.ExitStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.exitStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExitStmt([NotNull] BOSParser.ExitStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.filecopyStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFilecopyStmt([NotNull] BOSParser.FilecopyStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.filecopyStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFilecopyStmt([NotNull] BOSParser.FilecopyStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.forEachStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForEachStmt([NotNull] BOSParser.ForEachStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.forEachStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForEachStmt([NotNull] BOSParser.ForEachStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.forNextStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForNextStmt([NotNull] BOSParser.ForNextStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.forNextStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForNextStmt([NotNull] BOSParser.ForNextStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.functionStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionStmt([NotNull] BOSParser.FunctionStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.functionStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionStmt([NotNull] BOSParser.FunctionStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.getStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGetStmt([NotNull] BOSParser.GetStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.getStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGetStmt([NotNull] BOSParser.GetStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.goSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGoSubStmt([NotNull] BOSParser.GoSubStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.goSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGoSubStmt([NotNull] BOSParser.GoSubStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.goToStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGoToStmt([NotNull] BOSParser.GoToStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.goToStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGoToStmt([NotNull] BOSParser.GoToStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>inlineIfThenElse</c>
	/// labeled alternative in <see cref="BOSParser.ifThenElseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInlineIfThenElse([NotNull] BOSParser.InlineIfThenElseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>inlineIfThenElse</c>
	/// labeled alternative in <see cref="BOSParser.ifThenElseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInlineIfThenElse([NotNull] BOSParser.InlineIfThenElseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>blockIfThenElse</c>
	/// labeled alternative in <see cref="BOSParser.ifThenElseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockIfThenElse([NotNull] BOSParser.BlockIfThenElseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>blockIfThenElse</c>
	/// labeled alternative in <see cref="BOSParser.ifThenElseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockIfThenElse([NotNull] BOSParser.BlockIfThenElseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.ifBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfBlockStmt([NotNull] BOSParser.IfBlockStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.ifBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfBlockStmt([NotNull] BOSParser.IfBlockStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.ifConditionStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfConditionStmt([NotNull] BOSParser.IfConditionStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.ifConditionStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfConditionStmt([NotNull] BOSParser.IfConditionStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.ifElseIfBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfElseIfBlockStmt([NotNull] BOSParser.IfElseIfBlockStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.ifElseIfBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfElseIfBlockStmt([NotNull] BOSParser.IfElseIfBlockStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.ifElseBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfElseBlockStmt([NotNull] BOSParser.IfElseBlockStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.ifElseBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfElseBlockStmt([NotNull] BOSParser.IfElseBlockStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.implementsStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplementsStmt([NotNull] BOSParser.ImplementsStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.implementsStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplementsStmt([NotNull] BOSParser.ImplementsStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.inputStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInputStmt([NotNull] BOSParser.InputStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.inputStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInputStmt([NotNull] BOSParser.InputStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.killStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKillStmt([NotNull] BOSParser.KillStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.killStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKillStmt([NotNull] BOSParser.KillStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.letStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLetStmt([NotNull] BOSParser.LetStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.letStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLetStmt([NotNull] BOSParser.LetStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.lineInputStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLineInputStmt([NotNull] BOSParser.LineInputStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.lineInputStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLineInputStmt([NotNull] BOSParser.LineInputStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.loadStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoadStmt([NotNull] BOSParser.LoadStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.loadStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoadStmt([NotNull] BOSParser.LoadStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.lockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLockStmt([NotNull] BOSParser.LockStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.lockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLockStmt([NotNull] BOSParser.LockStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.lsetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLsetStmt([NotNull] BOSParser.LsetStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.lsetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLsetStmt([NotNull] BOSParser.LsetStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.macroIfThenElseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMacroIfThenElseStmt([NotNull] BOSParser.MacroIfThenElseStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.macroIfThenElseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMacroIfThenElseStmt([NotNull] BOSParser.MacroIfThenElseStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.macroIfBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMacroIfBlockStmt([NotNull] BOSParser.MacroIfBlockStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.macroIfBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMacroIfBlockStmt([NotNull] BOSParser.MacroIfBlockStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.macroElseIfBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMacroElseIfBlockStmt([NotNull] BOSParser.MacroElseIfBlockStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.macroElseIfBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMacroElseIfBlockStmt([NotNull] BOSParser.MacroElseIfBlockStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.macroElseBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMacroElseBlockStmt([NotNull] BOSParser.MacroElseBlockStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.macroElseBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMacroElseBlockStmt([NotNull] BOSParser.MacroElseBlockStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.midStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMidStmt([NotNull] BOSParser.MidStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.midStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMidStmt([NotNull] BOSParser.MidStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.mkdirStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMkdirStmt([NotNull] BOSParser.MkdirStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.mkdirStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMkdirStmt([NotNull] BOSParser.MkdirStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.nameStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNameStmt([NotNull] BOSParser.NameStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.nameStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNameStmt([NotNull] BOSParser.NameStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.onErrorStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOnErrorStmt([NotNull] BOSParser.OnErrorStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.onErrorStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOnErrorStmt([NotNull] BOSParser.OnErrorStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.onGoToStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOnGoToStmt([NotNull] BOSParser.OnGoToStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.onGoToStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOnGoToStmt([NotNull] BOSParser.OnGoToStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.onGoSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOnGoSubStmt([NotNull] BOSParser.OnGoSubStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.onGoSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOnGoSubStmt([NotNull] BOSParser.OnGoSubStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.openStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpenStmt([NotNull] BOSParser.OpenStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.openStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpenStmt([NotNull] BOSParser.OpenStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.outputList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutputList([NotNull] BOSParser.OutputListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.outputList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutputList([NotNull] BOSParser.OutputListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.outputList_Expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutputList_Expression([NotNull] BOSParser.OutputList_ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.outputList_Expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutputList_Expression([NotNull] BOSParser.OutputList_ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.printStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrintStmt([NotNull] BOSParser.PrintStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.printStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrintStmt([NotNull] BOSParser.PrintStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.propertyGetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyGetStmt([NotNull] BOSParser.PropertyGetStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.propertyGetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyGetStmt([NotNull] BOSParser.PropertyGetStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.propertySetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertySetStmt([NotNull] BOSParser.PropertySetStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.propertySetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertySetStmt([NotNull] BOSParser.PropertySetStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.propertyLetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyLetStmt([NotNull] BOSParser.PropertyLetStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.propertyLetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyLetStmt([NotNull] BOSParser.PropertyLetStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.putStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPutStmt([NotNull] BOSParser.PutStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.putStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPutStmt([NotNull] BOSParser.PutStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.raiseEventStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRaiseEventStmt([NotNull] BOSParser.RaiseEventStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.raiseEventStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRaiseEventStmt([NotNull] BOSParser.RaiseEventStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.randomizeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRandomizeStmt([NotNull] BOSParser.RandomizeStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.randomizeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRandomizeStmt([NotNull] BOSParser.RandomizeStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.redimStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRedimStmt([NotNull] BOSParser.RedimStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.redimStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRedimStmt([NotNull] BOSParser.RedimStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.redimSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRedimSubStmt([NotNull] BOSParser.RedimSubStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.redimSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRedimSubStmt([NotNull] BOSParser.RedimSubStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.resetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResetStmt([NotNull] BOSParser.ResetStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.resetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResetStmt([NotNull] BOSParser.ResetStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.resumeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterResumeStmt([NotNull] BOSParser.ResumeStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.resumeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitResumeStmt([NotNull] BOSParser.ResumeStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStmt([NotNull] BOSParser.ReturnStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStmt([NotNull] BOSParser.ReturnStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.rmdirStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRmdirStmt([NotNull] BOSParser.RmdirStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.rmdirStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRmdirStmt([NotNull] BOSParser.RmdirStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.rsetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRsetStmt([NotNull] BOSParser.RsetStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.rsetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRsetStmt([NotNull] BOSParser.RsetStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.savepictureStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSavepictureStmt([NotNull] BOSParser.SavepictureStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.savepictureStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSavepictureStmt([NotNull] BOSParser.SavepictureStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.saveSettingStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSaveSettingStmt([NotNull] BOSParser.SaveSettingStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.saveSettingStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSaveSettingStmt([NotNull] BOSParser.SaveSettingStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.seekStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSeekStmt([NotNull] BOSParser.SeekStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.seekStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSeekStmt([NotNull] BOSParser.SeekStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.selectCaseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectCaseStmt([NotNull] BOSParser.SelectCaseStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.selectCaseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectCaseStmt([NotNull] BOSParser.SelectCaseStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.sC_Case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSC_Case([NotNull] BOSParser.SC_CaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.sC_Case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSC_Case([NotNull] BOSParser.SC_CaseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>caseCondElse</c>
	/// labeled alternative in <see cref="BOSParser.sC_Cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseCondElse([NotNull] BOSParser.CaseCondElseContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>caseCondElse</c>
	/// labeled alternative in <see cref="BOSParser.sC_Cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseCondElse([NotNull] BOSParser.CaseCondElseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>caseCondExpr</c>
	/// labeled alternative in <see cref="BOSParser.sC_Cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseCondExpr([NotNull] BOSParser.CaseCondExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>caseCondExpr</c>
	/// labeled alternative in <see cref="BOSParser.sC_Cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseCondExpr([NotNull] BOSParser.CaseCondExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>caseCondExprIs</c>
	/// labeled alternative in <see cref="BOSParser.sC_CondExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseCondExprIs([NotNull] BOSParser.CaseCondExprIsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>caseCondExprIs</c>
	/// labeled alternative in <see cref="BOSParser.sC_CondExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseCondExprIs([NotNull] BOSParser.CaseCondExprIsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>caseCondExprValue</c>
	/// labeled alternative in <see cref="BOSParser.sC_CondExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseCondExprValue([NotNull] BOSParser.CaseCondExprValueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>caseCondExprValue</c>
	/// labeled alternative in <see cref="BOSParser.sC_CondExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseCondExprValue([NotNull] BOSParser.CaseCondExprValueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>caseCondExprTo</c>
	/// labeled alternative in <see cref="BOSParser.sC_CondExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseCondExprTo([NotNull] BOSParser.CaseCondExprToContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>caseCondExprTo</c>
	/// labeled alternative in <see cref="BOSParser.sC_CondExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseCondExprTo([NotNull] BOSParser.CaseCondExprToContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.sendkeysStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSendkeysStmt([NotNull] BOSParser.SendkeysStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.sendkeysStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSendkeysStmt([NotNull] BOSParser.SendkeysStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.setattrStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetattrStmt([NotNull] BOSParser.SetattrStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.setattrStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetattrStmt([NotNull] BOSParser.SetattrStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.setStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetStmt([NotNull] BOSParser.SetStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.setStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetStmt([NotNull] BOSParser.SetStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.stopStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStopStmt([NotNull] BOSParser.StopStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.stopStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStopStmt([NotNull] BOSParser.StopStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.subStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubStmt([NotNull] BOSParser.SubStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.subStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubStmt([NotNull] BOSParser.SubStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.timeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTimeStmt([NotNull] BOSParser.TimeStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.timeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTimeStmt([NotNull] BOSParser.TimeStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.typeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeStmt([NotNull] BOSParser.TypeStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.typeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeStmt([NotNull] BOSParser.TypeStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.typeStmt_Element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeStmt_Element([NotNull] BOSParser.TypeStmt_ElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.typeStmt_Element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeStmt_Element([NotNull] BOSParser.TypeStmt_ElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.typeOfStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeOfStmt([NotNull] BOSParser.TypeOfStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.typeOfStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeOfStmt([NotNull] BOSParser.TypeOfStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.unloadStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnloadStmt([NotNull] BOSParser.UnloadStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.unloadStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnloadStmt([NotNull] BOSParser.UnloadStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.unlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnlockStmt([NotNull] BOSParser.UnlockStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.unlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnlockStmt([NotNull] BOSParser.UnlockStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsDiv</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsDiv([NotNull] BOSParser.VsDivContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsDiv</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsDiv([NotNull] BOSParser.VsDivContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsNegation</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsNegation([NotNull] BOSParser.VsNegationContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsNegation</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsNegation([NotNull] BOSParser.VsNegationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsMinus</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsMinus([NotNull] BOSParser.VsMinusContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsMinus</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsMinus([NotNull] BOSParser.VsMinusContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsImp</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsImp([NotNull] BOSParser.VsImpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsImp</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsImp([NotNull] BOSParser.VsImpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsGeq</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsGeq([NotNull] BOSParser.VsGeqContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsGeq</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsGeq([NotNull] BOSParser.VsGeqContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsLt</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsLt([NotNull] BOSParser.VsLtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsLt</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsLt([NotNull] BOSParser.VsLtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsLiteral</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsLiteral([NotNull] BOSParser.VsLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsLiteral</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsLiteral([NotNull] BOSParser.VsLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsEqv</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsEqv([NotNull] BOSParser.VsEqvContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsEqv</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsEqv([NotNull] BOSParser.VsEqvContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsLike</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsLike([NotNull] BOSParser.VsLikeContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsLike</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsLike([NotNull] BOSParser.VsLikeContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsICS</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsICS([NotNull] BOSParser.VsICSContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsICS</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsICS([NotNull] BOSParser.VsICSContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsNeq</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsNeq([NotNull] BOSParser.VsNeqContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsNeq</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsNeq([NotNull] BOSParser.VsNeqContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsTypeOf</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsTypeOf([NotNull] BOSParser.VsTypeOfContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsTypeOf</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsTypeOf([NotNull] BOSParser.VsTypeOfContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsPow</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsPow([NotNull] BOSParser.VsPowContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsPow</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsPow([NotNull] BOSParser.VsPowContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsMult</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsMult([NotNull] BOSParser.VsMultContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsMult</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsMult([NotNull] BOSParser.VsMultContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsAssign</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsAssign([NotNull] BOSParser.VsAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsAssign</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsAssign([NotNull] BOSParser.VsAssignContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsAdd</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsAdd([NotNull] BOSParser.VsAddContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsAdd</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsAdd([NotNull] BOSParser.VsAddContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsPlus</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsPlus([NotNull] BOSParser.VsPlusContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsPlus</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsPlus([NotNull] BOSParser.VsPlusContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsStruct</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsStruct([NotNull] BOSParser.VsStructContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsStruct</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsStruct([NotNull] BOSParser.VsStructContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsOr</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsOr([NotNull] BOSParser.VsOrContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsOr</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsOr([NotNull] BOSParser.VsOrContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsAddressOf</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsAddressOf([NotNull] BOSParser.VsAddressOfContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsAddressOf</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsAddressOf([NotNull] BOSParser.VsAddressOfContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsMod</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsMod([NotNull] BOSParser.VsModContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsMod</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsMod([NotNull] BOSParser.VsModContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsNew</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsNew([NotNull] BOSParser.VsNewContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsNew</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsNew([NotNull] BOSParser.VsNewContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsNot</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsNot([NotNull] BOSParser.VsNotContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsNot</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsNot([NotNull] BOSParser.VsNotContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsAmp</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsAmp([NotNull] BOSParser.VsAmpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsAmp</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsAmp([NotNull] BOSParser.VsAmpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsMid</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsMid([NotNull] BOSParser.VsMidContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsMid</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsMid([NotNull] BOSParser.VsMidContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsAnd</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsAnd([NotNull] BOSParser.VsAndContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsAnd</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsAnd([NotNull] BOSParser.VsAndContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsEq</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsEq([NotNull] BOSParser.VsEqContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsEq</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsEq([NotNull] BOSParser.VsEqContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsIs</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsIs([NotNull] BOSParser.VsIsContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsIs</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsIs([NotNull] BOSParser.VsIsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsXor</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsXor([NotNull] BOSParser.VsXorContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsXor</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsXor([NotNull] BOSParser.VsXorContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsGt</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsGt([NotNull] BOSParser.VsGtContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsGt</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsGt([NotNull] BOSParser.VsGtContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>vsLeq</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVsLeq([NotNull] BOSParser.VsLeqContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>vsLeq</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVsLeq([NotNull] BOSParser.VsLeqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.variableStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableStmt([NotNull] BOSParser.VariableStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.variableStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableStmt([NotNull] BOSParser.VariableStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.variableListStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableListStmt([NotNull] BOSParser.VariableListStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.variableListStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableListStmt([NotNull] BOSParser.VariableListStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.variableSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableSubStmt([NotNull] BOSParser.VariableSubStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.variableSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableSubStmt([NotNull] BOSParser.VariableSubStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.whileWendStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileWendStmt([NotNull] BOSParser.WhileWendStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.whileWendStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileWendStmt([NotNull] BOSParser.WhileWendStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.widthStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWidthStmt([NotNull] BOSParser.WidthStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.widthStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWidthStmt([NotNull] BOSParser.WidthStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.withStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWithStmt([NotNull] BOSParser.WithStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.withStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWithStmt([NotNull] BOSParser.WithStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.writeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWriteStmt([NotNull] BOSParser.WriteStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.writeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWriteStmt([NotNull] BOSParser.WriteStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.explicitCallStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplicitCallStmt([NotNull] BOSParser.ExplicitCallStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.explicitCallStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplicitCallStmt([NotNull] BOSParser.ExplicitCallStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.eCS_ProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterECS_ProcedureCall([NotNull] BOSParser.ECS_ProcedureCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.eCS_ProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitECS_ProcedureCall([NotNull] BOSParser.ECS_ProcedureCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.eCS_MemberProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterECS_MemberProcedureCall([NotNull] BOSParser.ECS_MemberProcedureCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.eCS_MemberProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitECS_MemberProcedureCall([NotNull] BOSParser.ECS_MemberProcedureCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.implicitCallStmt_InBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplicitCallStmt_InBlock([NotNull] BOSParser.ImplicitCallStmt_InBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.implicitCallStmt_InBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplicitCallStmt_InBlock([NotNull] BOSParser.ImplicitCallStmt_InBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.iCS_B_ProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterICS_B_ProcedureCall([NotNull] BOSParser.ICS_B_ProcedureCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.iCS_B_ProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitICS_B_ProcedureCall([NotNull] BOSParser.ICS_B_ProcedureCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.iCS_B_MemberProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterICS_B_MemberProcedureCall([NotNull] BOSParser.ICS_B_MemberProcedureCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.iCS_B_MemberProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitICS_B_MemberProcedureCall([NotNull] BOSParser.ICS_B_MemberProcedureCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.implicitCallStmt_InStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplicitCallStmt_InStmt([NotNull] BOSParser.ImplicitCallStmt_InStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.implicitCallStmt_InStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplicitCallStmt_InStmt([NotNull] BOSParser.ImplicitCallStmt_InStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.iCS_S_VariableOrProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterICS_S_VariableOrProcedureCall([NotNull] BOSParser.ICS_S_VariableOrProcedureCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.iCS_S_VariableOrProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitICS_S_VariableOrProcedureCall([NotNull] BOSParser.ICS_S_VariableOrProcedureCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.iCS_S_ProcedureOrArrayCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterICS_S_ProcedureOrArrayCall([NotNull] BOSParser.ICS_S_ProcedureOrArrayCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.iCS_S_ProcedureOrArrayCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitICS_S_ProcedureOrArrayCall([NotNull] BOSParser.ICS_S_ProcedureOrArrayCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.iCS_S_NestedProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterICS_S_NestedProcedureCall([NotNull] BOSParser.ICS_S_NestedProcedureCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.iCS_S_NestedProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitICS_S_NestedProcedureCall([NotNull] BOSParser.ICS_S_NestedProcedureCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.iCS_S_MembersCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterICS_S_MembersCall([NotNull] BOSParser.ICS_S_MembersCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.iCS_S_MembersCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitICS_S_MembersCall([NotNull] BOSParser.ICS_S_MembersCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.iCS_S_MemberCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterICS_S_MemberCall([NotNull] BOSParser.ICS_S_MemberCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.iCS_S_MemberCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitICS_S_MemberCall([NotNull] BOSParser.ICS_S_MemberCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.iCS_S_DictionaryCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterICS_S_DictionaryCall([NotNull] BOSParser.ICS_S_DictionaryCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.iCS_S_DictionaryCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitICS_S_DictionaryCall([NotNull] BOSParser.ICS_S_DictionaryCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.argsCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgsCall([NotNull] BOSParser.ArgsCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.argsCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgsCall([NotNull] BOSParser.ArgsCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.argCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgCall([NotNull] BOSParser.ArgCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.argCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgCall([NotNull] BOSParser.ArgCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.dictionaryCallStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDictionaryCallStmt([NotNull] BOSParser.DictionaryCallStmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.dictionaryCallStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDictionaryCallStmt([NotNull] BOSParser.DictionaryCallStmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgList([NotNull] BOSParser.ArgListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgList([NotNull] BOSParser.ArgListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArg([NotNull] BOSParser.ArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArg([NotNull] BOSParser.ArgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.argDefaultValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgDefaultValue([NotNull] BOSParser.ArgDefaultValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.argDefaultValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgDefaultValue([NotNull] BOSParser.ArgDefaultValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.subscripts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubscripts([NotNull] BOSParser.SubscriptsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.subscripts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubscripts([NotNull] BOSParser.SubscriptsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.subscript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubscript([NotNull] BOSParser.SubscriptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.subscript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubscript([NotNull] BOSParser.SubscriptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.ambiguousIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAmbiguousIdentifier([NotNull] BOSParser.AmbiguousIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.ambiguousIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAmbiguousIdentifier([NotNull] BOSParser.AmbiguousIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.asTypeClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsTypeClause([NotNull] BOSParser.AsTypeClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.asTypeClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsTypeClause([NotNull] BOSParser.AsTypeClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.baseType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaseType([NotNull] BOSParser.BaseTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.baseType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaseType([NotNull] BOSParser.BaseTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.certainIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCertainIdentifier([NotNull] BOSParser.CertainIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.certainIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCertainIdentifier([NotNull] BOSParser.CertainIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.comparisonOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComparisonOperator([NotNull] BOSParser.ComparisonOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.comparisonOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComparisonOperator([NotNull] BOSParser.ComparisonOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.complexType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComplexType([NotNull] BOSParser.ComplexTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.complexType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComplexType([NotNull] BOSParser.ComplexTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.fieldLength"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldLength([NotNull] BOSParser.FieldLengthContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.fieldLength"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldLength([NotNull] BOSParser.FieldLengthContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.letterrange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLetterrange([NotNull] BOSParser.LetterrangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.letterrange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLetterrange([NotNull] BOSParser.LetterrangeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.lineLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLineLabel([NotNull] BOSParser.LineLabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.lineLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLineLabel([NotNull] BOSParser.LineLabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] BOSParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] BOSParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.publicPrivateVisibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPublicPrivateVisibility([NotNull] BOSParser.PublicPrivateVisibilityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.publicPrivateVisibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPublicPrivateVisibility([NotNull] BOSParser.PublicPrivateVisibilityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.publicPrivateGlobalVisibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPublicPrivateGlobalVisibility([NotNull] BOSParser.PublicPrivateGlobalVisibilityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.publicPrivateGlobalVisibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPublicPrivateGlobalVisibility([NotNull] BOSParser.PublicPrivateGlobalVisibilityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] BOSParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] BOSParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.typeHint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeHint([NotNull] BOSParser.TypeHintContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.typeHint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeHint([NotNull] BOSParser.TypeHintContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVisibility([NotNull] BOSParser.VisibilityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVisibility([NotNull] BOSParser.VisibilityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="BOSParser.ambiguousKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAmbiguousKeyword([NotNull] BOSParser.AmbiguousKeywordContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="BOSParser.ambiguousKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAmbiguousKeyword([NotNull] BOSParser.AmbiguousKeywordContext context);
}
