//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ../Grammar/BOS.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="BOSParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IBOSVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.startRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStartRule([NotNull] BOSParser.StartRuleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModule([NotNull] BOSParser.ModuleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.moduleReferences"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleReferences([NotNull] BOSParser.ModuleReferencesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.moduleReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleReference([NotNull] BOSParser.ModuleReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.moduleReferenceValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleReferenceValue([NotNull] BOSParser.ModuleReferenceValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.moduleReferenceComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleReferenceComponent([NotNull] BOSParser.ModuleReferenceComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.moduleHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleHeader([NotNull] BOSParser.ModuleHeaderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.moduleConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleConfig([NotNull] BOSParser.ModuleConfigContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.moduleConfigElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleConfigElement([NotNull] BOSParser.ModuleConfigElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.moduleAttributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleAttributes([NotNull] BOSParser.ModuleAttributesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.moduleOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleOptions([NotNull] BOSParser.ModuleOptionsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>optionBaseStmt</c>
	/// labeled alternative in <see cref="BOSParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionBaseStmt([NotNull] BOSParser.OptionBaseStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>optionCompareStmt</c>
	/// labeled alternative in <see cref="BOSParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionCompareStmt([NotNull] BOSParser.OptionCompareStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>optionExplicitStmt</c>
	/// labeled alternative in <see cref="BOSParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionExplicitStmt([NotNull] BOSParser.OptionExplicitStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>optionPrivateModuleStmt</c>
	/// labeled alternative in <see cref="BOSParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionPrivateModuleStmt([NotNull] BOSParser.OptionPrivateModuleStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.moduleBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleBody([NotNull] BOSParser.ModuleBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.moduleBodyElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleBodyElement([NotNull] BOSParser.ModuleBodyElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.controlProperties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitControlProperties([NotNull] BOSParser.ControlPropertiesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.cp_Properties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCp_Properties([NotNull] BOSParser.Cp_PropertiesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.cp_SingleProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCp_SingleProperty([NotNull] BOSParser.Cp_SinglePropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.cp_PropertyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCp_PropertyName([NotNull] BOSParser.Cp_PropertyNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.cp_PropertyValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCp_PropertyValue([NotNull] BOSParser.Cp_PropertyValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.cp_NestedProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCp_NestedProperty([NotNull] BOSParser.Cp_NestedPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.cp_ControlType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCp_ControlType([NotNull] BOSParser.Cp_ControlTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.cp_ControlIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCp_ControlIdentifier([NotNull] BOSParser.Cp_ControlIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.moduleBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleBlock([NotNull] BOSParser.ModuleBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.attributeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeStmt([NotNull] BOSParser.AttributeStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] BOSParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.blockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockStmt([NotNull] BOSParser.BlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.appActivateStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppActivateStmt([NotNull] BOSParser.AppActivateStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.beepStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBeepStmt([NotNull] BOSParser.BeepStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.chDirStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChDirStmt([NotNull] BOSParser.ChDirStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.chDriveStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChDriveStmt([NotNull] BOSParser.ChDriveStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.closeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCloseStmt([NotNull] BOSParser.CloseStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.constStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstStmt([NotNull] BOSParser.ConstStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.constSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstSubStmt([NotNull] BOSParser.ConstSubStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.dateStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDateStmt([NotNull] BOSParser.DateStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.declareStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareStmt([NotNull] BOSParser.DeclareStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.deftypeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeftypeStmt([NotNull] BOSParser.DeftypeStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.deleteSettingStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeleteSettingStmt([NotNull] BOSParser.DeleteSettingStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.doLoopStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoLoopStmt([NotNull] BOSParser.DoLoopStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.endStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEndStmt([NotNull] BOSParser.EndStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.enumerationStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumerationStmt([NotNull] BOSParser.EnumerationStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.enumerationStmt_Constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumerationStmt_Constant([NotNull] BOSParser.EnumerationStmt_ConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.eraseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEraseStmt([NotNull] BOSParser.EraseStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.errorStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitErrorStmt([NotNull] BOSParser.ErrorStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.eventStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEventStmt([NotNull] BOSParser.EventStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.exitStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExitStmt([NotNull] BOSParser.ExitStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.filecopyStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFilecopyStmt([NotNull] BOSParser.FilecopyStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.forEachStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForEachStmt([NotNull] BOSParser.ForEachStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.forNextStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForNextStmt([NotNull] BOSParser.ForNextStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.functionStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionStmt([NotNull] BOSParser.FunctionStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.getStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGetStmt([NotNull] BOSParser.GetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.goSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGoSubStmt([NotNull] BOSParser.GoSubStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.goToStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGoToStmt([NotNull] BOSParser.GoToStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>inlineIfThenElse</c>
	/// labeled alternative in <see cref="BOSParser.ifThenElseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInlineIfThenElse([NotNull] BOSParser.InlineIfThenElseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>blockIfThenElse</c>
	/// labeled alternative in <see cref="BOSParser.ifThenElseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockIfThenElse([NotNull] BOSParser.BlockIfThenElseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.ifBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfBlockStmt([NotNull] BOSParser.IfBlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.ifConditionStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfConditionStmt([NotNull] BOSParser.IfConditionStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.ifElseIfBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfElseIfBlockStmt([NotNull] BOSParser.IfElseIfBlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.ifElseBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfElseBlockStmt([NotNull] BOSParser.IfElseBlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.implementsStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImplementsStmt([NotNull] BOSParser.ImplementsStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.inputStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInputStmt([NotNull] BOSParser.InputStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.killStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKillStmt([NotNull] BOSParser.KillStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.letStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLetStmt([NotNull] BOSParser.LetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.lineInputStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLineInputStmt([NotNull] BOSParser.LineInputStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.loadStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoadStmt([NotNull] BOSParser.LoadStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.lockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLockStmt([NotNull] BOSParser.LockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.lsetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLsetStmt([NotNull] BOSParser.LsetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.macroIfThenElseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacroIfThenElseStmt([NotNull] BOSParser.MacroIfThenElseStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.macroIfBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacroIfBlockStmt([NotNull] BOSParser.MacroIfBlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.macroElseIfBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacroElseIfBlockStmt([NotNull] BOSParser.MacroElseIfBlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.macroElseBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacroElseBlockStmt([NotNull] BOSParser.MacroElseBlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.midStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMidStmt([NotNull] BOSParser.MidStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.mkdirStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMkdirStmt([NotNull] BOSParser.MkdirStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.nameStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameStmt([NotNull] BOSParser.NameStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.onErrorStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOnErrorStmt([NotNull] BOSParser.OnErrorStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.onGoToStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOnGoToStmt([NotNull] BOSParser.OnGoToStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.onGoSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOnGoSubStmt([NotNull] BOSParser.OnGoSubStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.openStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpenStmt([NotNull] BOSParser.OpenStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.outputList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutputList([NotNull] BOSParser.OutputListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.outputList_Expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutputList_Expression([NotNull] BOSParser.OutputList_ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.printStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintStmt([NotNull] BOSParser.PrintStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.propertyGetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyGetStmt([NotNull] BOSParser.PropertyGetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.propertySetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertySetStmt([NotNull] BOSParser.PropertySetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.propertyLetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyLetStmt([NotNull] BOSParser.PropertyLetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.putStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPutStmt([NotNull] BOSParser.PutStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.raiseEventStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaiseEventStmt([NotNull] BOSParser.RaiseEventStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.randomizeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRandomizeStmt([NotNull] BOSParser.RandomizeStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.redimStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRedimStmt([NotNull] BOSParser.RedimStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.redimSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRedimSubStmt([NotNull] BOSParser.RedimSubStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.resetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResetStmt([NotNull] BOSParser.ResetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.resumeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResumeStmt([NotNull] BOSParser.ResumeStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStmt([NotNull] BOSParser.ReturnStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.rmdirStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRmdirStmt([NotNull] BOSParser.RmdirStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.rsetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRsetStmt([NotNull] BOSParser.RsetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.savepictureStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSavepictureStmt([NotNull] BOSParser.SavepictureStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.saveSettingStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSaveSettingStmt([NotNull] BOSParser.SaveSettingStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.seekStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSeekStmt([NotNull] BOSParser.SeekStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.selectCaseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectCaseStmt([NotNull] BOSParser.SelectCaseStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.sC_Case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSC_Case([NotNull] BOSParser.SC_CaseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>caseCondElse</c>
	/// labeled alternative in <see cref="BOSParser.sC_Cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseCondElse([NotNull] BOSParser.CaseCondElseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>caseCondExpr</c>
	/// labeled alternative in <see cref="BOSParser.sC_Cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseCondExpr([NotNull] BOSParser.CaseCondExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>caseCondExprIs</c>
	/// labeled alternative in <see cref="BOSParser.sC_CondExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseCondExprIs([NotNull] BOSParser.CaseCondExprIsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>caseCondExprValue</c>
	/// labeled alternative in <see cref="BOSParser.sC_CondExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseCondExprValue([NotNull] BOSParser.CaseCondExprValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>caseCondExprTo</c>
	/// labeled alternative in <see cref="BOSParser.sC_CondExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseCondExprTo([NotNull] BOSParser.CaseCondExprToContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.sendkeysStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSendkeysStmt([NotNull] BOSParser.SendkeysStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.setattrStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetattrStmt([NotNull] BOSParser.SetattrStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.setStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetStmt([NotNull] BOSParser.SetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.stopStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStopStmt([NotNull] BOSParser.StopStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.subStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubStmt([NotNull] BOSParser.SubStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.timeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeStmt([NotNull] BOSParser.TimeStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.typeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeStmt([NotNull] BOSParser.TypeStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.typeStmt_Element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeStmt_Element([NotNull] BOSParser.TypeStmt_ElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.typeOfStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeOfStmt([NotNull] BOSParser.TypeOfStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.unloadStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnloadStmt([NotNull] BOSParser.UnloadStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.unlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnlockStmt([NotNull] BOSParser.UnlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsDiv</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsDiv([NotNull] BOSParser.VsDivContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsNegation</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsNegation([NotNull] BOSParser.VsNegationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsMinus</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsMinus([NotNull] BOSParser.VsMinusContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsImp</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsImp([NotNull] BOSParser.VsImpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsGeq</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsGeq([NotNull] BOSParser.VsGeqContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsLt</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsLt([NotNull] BOSParser.VsLtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsLiteral</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsLiteral([NotNull] BOSParser.VsLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsEqv</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsEqv([NotNull] BOSParser.VsEqvContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsLike</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsLike([NotNull] BOSParser.VsLikeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsICS</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsICS([NotNull] BOSParser.VsICSContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsNeq</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsNeq([NotNull] BOSParser.VsNeqContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsTypeOf</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsTypeOf([NotNull] BOSParser.VsTypeOfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsPow</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsPow([NotNull] BOSParser.VsPowContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsMult</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsMult([NotNull] BOSParser.VsMultContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsAssign</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsAssign([NotNull] BOSParser.VsAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsAdd</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsAdd([NotNull] BOSParser.VsAddContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsPlus</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsPlus([NotNull] BOSParser.VsPlusContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsStruct</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsStruct([NotNull] BOSParser.VsStructContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsOr</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsOr([NotNull] BOSParser.VsOrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsAddressOf</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsAddressOf([NotNull] BOSParser.VsAddressOfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsMod</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsMod([NotNull] BOSParser.VsModContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsNew</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsNew([NotNull] BOSParser.VsNewContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsNot</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsNot([NotNull] BOSParser.VsNotContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsAmp</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsAmp([NotNull] BOSParser.VsAmpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsMid</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsMid([NotNull] BOSParser.VsMidContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsAnd</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsAnd([NotNull] BOSParser.VsAndContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsEq</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsEq([NotNull] BOSParser.VsEqContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsIs</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsIs([NotNull] BOSParser.VsIsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsXor</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsXor([NotNull] BOSParser.VsXorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsGt</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsGt([NotNull] BOSParser.VsGtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsLeq</c>
	/// labeled alternative in <see cref="BOSParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsLeq([NotNull] BOSParser.VsLeqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.variableStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableStmt([NotNull] BOSParser.VariableStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.variableListStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableListStmt([NotNull] BOSParser.VariableListStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.variableSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableSubStmt([NotNull] BOSParser.VariableSubStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.whileWendStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileWendStmt([NotNull] BOSParser.WhileWendStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.widthStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWidthStmt([NotNull] BOSParser.WidthStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.withStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWithStmt([NotNull] BOSParser.WithStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.writeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWriteStmt([NotNull] BOSParser.WriteStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.explicitCallStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicitCallStmt([NotNull] BOSParser.ExplicitCallStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.eCS_ProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitECS_ProcedureCall([NotNull] BOSParser.ECS_ProcedureCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.eCS_MemberProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitECS_MemberProcedureCall([NotNull] BOSParser.ECS_MemberProcedureCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.implicitCallStmt_InBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImplicitCallStmt_InBlock([NotNull] BOSParser.ImplicitCallStmt_InBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.iCS_B_ProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitICS_B_ProcedureCall([NotNull] BOSParser.ICS_B_ProcedureCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.iCS_B_MemberProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitICS_B_MemberProcedureCall([NotNull] BOSParser.ICS_B_MemberProcedureCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.implicitCallStmt_InStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImplicitCallStmt_InStmt([NotNull] BOSParser.ImplicitCallStmt_InStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.iCS_S_VariableOrProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitICS_S_VariableOrProcedureCall([NotNull] BOSParser.ICS_S_VariableOrProcedureCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.iCS_S_ProcedureOrArrayCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitICS_S_ProcedureOrArrayCall([NotNull] BOSParser.ICS_S_ProcedureOrArrayCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.iCS_S_NestedProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitICS_S_NestedProcedureCall([NotNull] BOSParser.ICS_S_NestedProcedureCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.iCS_S_MembersCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitICS_S_MembersCall([NotNull] BOSParser.ICS_S_MembersCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.iCS_S_MemberCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitICS_S_MemberCall([NotNull] BOSParser.ICS_S_MemberCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.iCS_S_DictionaryCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitICS_S_DictionaryCall([NotNull] BOSParser.ICS_S_DictionaryCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.argsCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgsCall([NotNull] BOSParser.ArgsCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.argCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgCall([NotNull] BOSParser.ArgCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.dictionaryCallStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDictionaryCallStmt([NotNull] BOSParser.DictionaryCallStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgList([NotNull] BOSParser.ArgListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArg([NotNull] BOSParser.ArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.argDefaultValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgDefaultValue([NotNull] BOSParser.ArgDefaultValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.subscripts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubscripts([NotNull] BOSParser.SubscriptsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.subscript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubscript([NotNull] BOSParser.SubscriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.ambiguousIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAmbiguousIdentifier([NotNull] BOSParser.AmbiguousIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.asTypeClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsTypeClause([NotNull] BOSParser.AsTypeClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.baseType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseType([NotNull] BOSParser.BaseTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.certainIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCertainIdentifier([NotNull] BOSParser.CertainIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.comparisonOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparisonOperator([NotNull] BOSParser.ComparisonOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.complexType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplexType([NotNull] BOSParser.ComplexTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.fieldLength"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldLength([NotNull] BOSParser.FieldLengthContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.letterrange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLetterrange([NotNull] BOSParser.LetterrangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.lineLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLineLabel([NotNull] BOSParser.LineLabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] BOSParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.publicPrivateVisibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPublicPrivateVisibility([NotNull] BOSParser.PublicPrivateVisibilityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.publicPrivateGlobalVisibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPublicPrivateGlobalVisibility([NotNull] BOSParser.PublicPrivateGlobalVisibilityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] BOSParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.typeHint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeHint([NotNull] BOSParser.TypeHintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVisibility([NotNull] BOSParser.VisibilityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BOSParser.ambiguousKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAmbiguousKeyword([NotNull] BOSParser.AmbiguousKeywordContext context);
}
