//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Grammar/Bos.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="BosParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IBosVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.startRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStartRule([NotNull] BosParser.StartRuleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.module"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModule([NotNull] BosParser.ModuleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.moduleReferences"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleReferences([NotNull] BosParser.ModuleReferencesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.moduleImports"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleImports([NotNull] BosParser.ModuleImportsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.moduleReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleReference([NotNull] BosParser.ModuleReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.moduleReferenceValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleReferenceValue([NotNull] BosParser.ModuleReferenceValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.moduleReferenceComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleReferenceComponent([NotNull] BosParser.ModuleReferenceComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.moduleHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleHeader([NotNull] BosParser.ModuleHeaderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.moduleConfig"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleConfig([NotNull] BosParser.ModuleConfigContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.moduleConfigElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleConfigElement([NotNull] BosParser.ModuleConfigElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.moduleAttributes"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleAttributes([NotNull] BosParser.ModuleAttributesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.moduleOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleOptions([NotNull] BosParser.ModuleOptionsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>optionBaseStmt</c>
	/// labeled alternative in <see cref="BosParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionBaseStmt([NotNull] BosParser.OptionBaseStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>optionCompareStmt</c>
	/// labeled alternative in <see cref="BosParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionCompareStmt([NotNull] BosParser.OptionCompareStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>optionExplicitStmt</c>
	/// labeled alternative in <see cref="BosParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionExplicitStmt([NotNull] BosParser.OptionExplicitStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>optionPrivateModuleStmt</c>
	/// labeled alternative in <see cref="BosParser.moduleOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionPrivateModuleStmt([NotNull] BosParser.OptionPrivateModuleStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.moduleBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleBody([NotNull] BosParser.ModuleBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.moduleBodyElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleBodyElement([NotNull] BosParser.ModuleBodyElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassBody([NotNull] BosParser.ClassBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.classBodyElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassBodyElement([NotNull] BosParser.ClassBodyElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.controlProperties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitControlProperties([NotNull] BosParser.ControlPropertiesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.cp_Properties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCp_Properties([NotNull] BosParser.Cp_PropertiesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.cp_SingleProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCp_SingleProperty([NotNull] BosParser.Cp_SinglePropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.cp_PropertyName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCp_PropertyName([NotNull] BosParser.Cp_PropertyNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.cp_PropertyValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCp_PropertyValue([NotNull] BosParser.Cp_PropertyValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.cp_NestedProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCp_NestedProperty([NotNull] BosParser.Cp_NestedPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.cp_ControlType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCp_ControlType([NotNull] BosParser.Cp_ControlTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.cp_ControlIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCp_ControlIdentifier([NotNull] BosParser.Cp_ControlIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.moduleBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleBlock([NotNull] BosParser.ModuleBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.importStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImportStmt([NotNull] BosParser.ImportStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.attributeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeStmt([NotNull] BosParser.AttributeStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] BosParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.blockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockStmt([NotNull] BosParser.BlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.appActivateStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAppActivateStmt([NotNull] BosParser.AppActivateStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.beepStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBeepStmt([NotNull] BosParser.BeepStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.chDirStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChDirStmt([NotNull] BosParser.ChDirStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.chDriveStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChDriveStmt([NotNull] BosParser.ChDriveStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.classStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassStmt([NotNull] BosParser.ClassStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.closeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCloseStmt([NotNull] BosParser.CloseStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.constStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstStmt([NotNull] BosParser.ConstStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.constSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstSubStmt([NotNull] BosParser.ConstSubStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.dateStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDateStmt([NotNull] BosParser.DateStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.declareStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclareStmt([NotNull] BosParser.DeclareStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.deftypeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeftypeStmt([NotNull] BosParser.DeftypeStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.deleteSettingStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeleteSettingStmt([NotNull] BosParser.DeleteSettingStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.doLoopStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDoLoopStmt([NotNull] BosParser.DoLoopStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.endStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEndStmt([NotNull] BosParser.EndStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.enumerationStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumerationStmt([NotNull] BosParser.EnumerationStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.enumerationStmt_Constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumerationStmt_Constant([NotNull] BosParser.EnumerationStmt_ConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.eraseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEraseStmt([NotNull] BosParser.EraseStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.errorStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitErrorStmt([NotNull] BosParser.ErrorStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.eventStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEventStmt([NotNull] BosParser.EventStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.exitStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExitStmt([NotNull] BosParser.ExitStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.filecopyStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFilecopyStmt([NotNull] BosParser.FilecopyStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.forEachStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForEachStmt([NotNull] BosParser.ForEachStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.forNextStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForNextStmt([NotNull] BosParser.ForNextStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.functionStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionStmt([NotNull] BosParser.FunctionStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.getStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGetStmt([NotNull] BosParser.GetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.goSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGoSubStmt([NotNull] BosParser.GoSubStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.goToStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGoToStmt([NotNull] BosParser.GoToStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>inlineIfThenElse</c>
	/// labeled alternative in <see cref="BosParser.ifThenElseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInlineIfThenElse([NotNull] BosParser.InlineIfThenElseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>blockIfThenElse</c>
	/// labeled alternative in <see cref="BosParser.ifThenElseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockIfThenElse([NotNull] BosParser.BlockIfThenElseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.ifBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfBlockStmt([NotNull] BosParser.IfBlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.ifConditionStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfConditionStmt([NotNull] BosParser.IfConditionStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.ifElseIfBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfElseIfBlockStmt([NotNull] BosParser.IfElseIfBlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.ifElseBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfElseBlockStmt([NotNull] BosParser.IfElseBlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.implementsStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImplementsStmt([NotNull] BosParser.ImplementsStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.inputStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInputStmt([NotNull] BosParser.InputStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.killStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKillStmt([NotNull] BosParser.KillStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.letStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLetStmt([NotNull] BosParser.LetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.lineInputStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLineInputStmt([NotNull] BosParser.LineInputStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.loadStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoadStmt([NotNull] BosParser.LoadStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.lockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLockStmt([NotNull] BosParser.LockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.lsetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLsetStmt([NotNull] BosParser.LsetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.macroIfThenElseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacroIfThenElseStmt([NotNull] BosParser.MacroIfThenElseStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.macroIfBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacroIfBlockStmt([NotNull] BosParser.MacroIfBlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.macroElseIfBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacroElseIfBlockStmt([NotNull] BosParser.MacroElseIfBlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.macroElseBlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacroElseBlockStmt([NotNull] BosParser.MacroElseBlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.midStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMidStmt([NotNull] BosParser.MidStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.mkdirStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMkdirStmt([NotNull] BosParser.MkdirStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.nameStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameStmt([NotNull] BosParser.NameStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.onErrorStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOnErrorStmt([NotNull] BosParser.OnErrorStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.onGoToStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOnGoToStmt([NotNull] BosParser.OnGoToStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.onGoSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOnGoSubStmt([NotNull] BosParser.OnGoSubStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.openStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpenStmt([NotNull] BosParser.OpenStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.outputList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutputList([NotNull] BosParser.OutputListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.outputList_Expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutputList_Expression([NotNull] BosParser.OutputList_ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.printStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintStmt([NotNull] BosParser.PrintStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.propertyGetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyGetStmt([NotNull] BosParser.PropertyGetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.propertySetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertySetStmt([NotNull] BosParser.PropertySetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.propertyLetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyLetStmt([NotNull] BosParser.PropertyLetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.putStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPutStmt([NotNull] BosParser.PutStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.raiseEventStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaiseEventStmt([NotNull] BosParser.RaiseEventStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.randomizeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRandomizeStmt([NotNull] BosParser.RandomizeStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.redimStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRedimStmt([NotNull] BosParser.RedimStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.redimSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRedimSubStmt([NotNull] BosParser.RedimSubStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.resetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResetStmt([NotNull] BosParser.ResetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.resumeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResumeStmt([NotNull] BosParser.ResumeStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.returnStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStmt([NotNull] BosParser.ReturnStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.rmdirStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRmdirStmt([NotNull] BosParser.RmdirStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.rsetStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRsetStmt([NotNull] BosParser.RsetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.savepictureStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSavepictureStmt([NotNull] BosParser.SavepictureStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.saveSettingStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSaveSettingStmt([NotNull] BosParser.SaveSettingStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.seekStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSeekStmt([NotNull] BosParser.SeekStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.selectCaseStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectCaseStmt([NotNull] BosParser.SelectCaseStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.sC_Case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSC_Case([NotNull] BosParser.SC_CaseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>caseCondElse</c>
	/// labeled alternative in <see cref="BosParser.sC_Cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseCondElse([NotNull] BosParser.CaseCondElseContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>caseCondExpr</c>
	/// labeled alternative in <see cref="BosParser.sC_Cond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseCondExpr([NotNull] BosParser.CaseCondExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>caseCondExprIs</c>
	/// labeled alternative in <see cref="BosParser.sC_CondExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseCondExprIs([NotNull] BosParser.CaseCondExprIsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>caseCondExprValue</c>
	/// labeled alternative in <see cref="BosParser.sC_CondExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseCondExprValue([NotNull] BosParser.CaseCondExprValueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>caseCondExprTo</c>
	/// labeled alternative in <see cref="BosParser.sC_CondExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaseCondExprTo([NotNull] BosParser.CaseCondExprToContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.sendkeysStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSendkeysStmt([NotNull] BosParser.SendkeysStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.setattrStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetattrStmt([NotNull] BosParser.SetattrStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.setStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetStmt([NotNull] BosParser.SetStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.stopStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStopStmt([NotNull] BosParser.StopStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.subStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubStmt([NotNull] BosParser.SubStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.timeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTimeStmt([NotNull] BosParser.TimeStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.typeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeStmt([NotNull] BosParser.TypeStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.typeStmt_Element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeStmt_Element([NotNull] BosParser.TypeStmt_ElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.typeOfStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeOfStmt([NotNull] BosParser.TypeOfStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.unloadStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnloadStmt([NotNull] BosParser.UnloadStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.unlockStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnlockStmt([NotNull] BosParser.UnlockStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsStruct</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsStruct([NotNull] BosParser.VsStructContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsAdd</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsAdd([NotNull] BosParser.VsAddContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsLt</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsLt([NotNull] BosParser.VsLtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsAddressOf</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsAddressOf([NotNull] BosParser.VsAddressOfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsNew</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsNew([NotNull] BosParser.VsNewContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsMult</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsMult([NotNull] BosParser.VsMultContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsNegation</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsNegation([NotNull] BosParser.VsNegationContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsAssign</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsAssign([NotNull] BosParser.VsAssignContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsDiv</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsDiv([NotNull] BosParser.VsDivContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsLike</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsLike([NotNull] BosParser.VsLikeContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsPlus</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsPlus([NotNull] BosParser.VsPlusContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsNot</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsNot([NotNull] BosParser.VsNotContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsGeq</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsGeq([NotNull] BosParser.VsGeqContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsTypeOf</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsTypeOf([NotNull] BosParser.VsTypeOfContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsICS</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsICS([NotNull] BosParser.VsICSContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsNeq</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsNeq([NotNull] BosParser.VsNeqContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsXor</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsXor([NotNull] BosParser.VsXorContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsAnd</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsAnd([NotNull] BosParser.VsAndContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsPow</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsPow([NotNull] BosParser.VsPowContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsLeq</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsLeq([NotNull] BosParser.VsLeqContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsIs</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsIs([NotNull] BosParser.VsIsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsMod</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsMod([NotNull] BosParser.VsModContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsAmp</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsAmp([NotNull] BosParser.VsAmpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsOr</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsOr([NotNull] BosParser.VsOrContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsMinus</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsMinus([NotNull] BosParser.VsMinusContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsLiteral</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsLiteral([NotNull] BosParser.VsLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsEqv</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsEqv([NotNull] BosParser.VsEqvContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsImp</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsImp([NotNull] BosParser.VsImpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsGt</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsGt([NotNull] BosParser.VsGtContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsEq</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsEq([NotNull] BosParser.VsEqContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vsMid</c>
	/// labeled alternative in <see cref="BosParser.valueStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVsMid([NotNull] BosParser.VsMidContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.variableStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableStmt([NotNull] BosParser.VariableStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.variableListStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableListStmt([NotNull] BosParser.VariableListStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.variableSubStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableSubStmt([NotNull] BosParser.VariableSubStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.whileWendStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileWendStmt([NotNull] BosParser.WhileWendStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.widthStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWidthStmt([NotNull] BosParser.WidthStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.withStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWithStmt([NotNull] BosParser.WithStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.writeStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWriteStmt([NotNull] BosParser.WriteStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.explicitCallStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicitCallStmt([NotNull] BosParser.ExplicitCallStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.eCS_ProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitECS_ProcedureCall([NotNull] BosParser.ECS_ProcedureCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.eCS_MemberProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitECS_MemberProcedureCall([NotNull] BosParser.ECS_MemberProcedureCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.implicitCallStmt_InBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImplicitCallStmt_InBlock([NotNull] BosParser.ImplicitCallStmt_InBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.iCS_B_ProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitICS_B_ProcedureCall([NotNull] BosParser.ICS_B_ProcedureCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.iCS_B_MemberProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitICS_B_MemberProcedureCall([NotNull] BosParser.ICS_B_MemberProcedureCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.implicitCallStmt_InStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImplicitCallStmt_InStmt([NotNull] BosParser.ImplicitCallStmt_InStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.iCS_S_VariableOrProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitICS_S_VariableOrProcedureCall([NotNull] BosParser.ICS_S_VariableOrProcedureCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.iCS_S_ProcedureOrArrayCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitICS_S_ProcedureOrArrayCall([NotNull] BosParser.ICS_S_ProcedureOrArrayCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.iCS_S_NestedProcedureCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitICS_S_NestedProcedureCall([NotNull] BosParser.ICS_S_NestedProcedureCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.iCS_S_MembersCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitICS_S_MembersCall([NotNull] BosParser.ICS_S_MembersCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.iCS_S_MemberCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitICS_S_MemberCall([NotNull] BosParser.ICS_S_MemberCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.iCS_S_DictionaryCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitICS_S_DictionaryCall([NotNull] BosParser.ICS_S_DictionaryCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.argsCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgsCall([NotNull] BosParser.ArgsCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.argCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgCall([NotNull] BosParser.ArgCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.dictionaryCallStmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDictionaryCallStmt([NotNull] BosParser.DictionaryCallStmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgList([NotNull] BosParser.ArgListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArg([NotNull] BosParser.ArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.argDefaultValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgDefaultValue([NotNull] BosParser.ArgDefaultValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.subscripts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubscripts([NotNull] BosParser.SubscriptsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.subscript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubscript([NotNull] BosParser.SubscriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.ambiguousIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAmbiguousIdentifier([NotNull] BosParser.AmbiguousIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.asTypeClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsTypeClause([NotNull] BosParser.AsTypeClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.baseType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseType([NotNull] BosParser.BaseTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.certainIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCertainIdentifier([NotNull] BosParser.CertainIdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.comparisonOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparisonOperator([NotNull] BosParser.ComparisonOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.complexType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComplexType([NotNull] BosParser.ComplexTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.fieldLength"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldLength([NotNull] BosParser.FieldLengthContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.letterrange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLetterrange([NotNull] BosParser.LetterrangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.lineLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLineLabel([NotNull] BosParser.LineLabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] BosParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.publicPrivateVisibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPublicPrivateVisibility([NotNull] BosParser.PublicPrivateVisibilityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.publicPrivateGlobalVisibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPublicPrivateGlobalVisibility([NotNull] BosParser.PublicPrivateGlobalVisibilityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] BosParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.typeHint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeHint([NotNull] BosParser.TypeHintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.visibility"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVisibility([NotNull] BosParser.VisibilityContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BosParser.ambiguousKeyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAmbiguousKeyword([NotNull] BosParser.AmbiguousKeywordContext context);
}
